### ISSUE TITLE
support for Julia 1.x

### ISSUE THREAD

**Issue by jamie-arcc** [lakras/matlab-to-julia#2]
There have been significant language changes, especially between 0.6.x and 1.0.  After 1.0 it should remain stable.  It would be good for the translator to support this.

**Comment by lakras** [comment]
Hi hi! I agree!!!! Sorry about the 5-month, 7-day delay. I've updated the translator to support (hopefully) most of the changes. It is ALSO now fully on GitHub, with unit tests and everything—if there is something you would like to add or correct please feel welcome to submit a pull request (or open a new issue).
