### ISSUE TITLE
Consider hosting the web page from GitHub Pages

### ISSUE THREAD

**Issue by waldyrious** [lakras/matlab-to-julia#3]
[GitHub Pages](https://pages.github.com/) allows the contents of a repository (either a folder in the `master` branch, or a separate branch) to be served in a URL like https://lakras.github.io/matlab-to-julia.

Please consider hosting the [web page](http://sciencecow.mit.edu/matlab-to-julia/) in that manner, so that it can also be collaboratively developed. For example, I noticed a dead link there, and would also like to add a link to this repository, both of which are changes I would gladly have submitted as PRs.

Note that the current URL can still be preserved so that no links are broken :)

**Comment by lakras** [comment]
Excellent idea! I was just thinking that I would like to move it over to github fully. I'll let you know here once it's done (soon! within the week). Thank you!

**Comment by waldyrious** [comment]
That's great to hear! Looking forward to that :)

**Comment by lakras** [comment]
It is done! That was fun. Thank you so much for the suggestion and for the push in the right direction.

**Comment by waldyrious** [comment]
Great news! You might want to also add the link https://lakras.github.io/matlab-to-julia to the repository description (under the title, next to "Translates MATLAB source code into Julia.") to make it more accessible and visible.

**Comment by lakras** [comment]
Great idea! URL added. (Not sure how to make it a link, but at the very least it is a copy/paste-able URL.)

**Comment by waldyrious** [comment]
> Not sure how to make it a link

It does show up as a link to me. In any case, you may have missed it but when you edit the repository tagline, there is also a dedicated field for a URL next to it.

**Comment by lakras** [comment]
Yes! I was thinking in search results (the contents of the dedicated URL field are not displayed there), like https://github.com/search?q=matlab+julia , and also on https://github.com/lakras . But URL alone is good enough, I think.

**Comment by waldyrious** [comment]
Ah, I see what you mean. I almost wrote that the URL would be available in search results in my comment above, but ran the same search you linked to and noticed that no URLs show up there. I believe they used to.

Nice idea adding the link to the main description, but indeed it doesn't seem to work well at the moment. Hopefully they'll fix that in the future.
